"""Generate infra/postgres-init/01_seed.sql from the same security seed data,
so the Trino+Postgres docker stack mirrors the SQLite test data.

Run:  python scripts/export_postgres_seed.py
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import seed_security as s  # noqa: E402

OUT_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "infra", "postgres-init"))
os.makedirs(OUT_DIR, exist_ok=True)
OUT = os.path.join(OUT_DIR, "01_seed.sql")


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def rows(values):
    return ",\n".join("(" + ", ".join(q(c) for c in row) + ")" for row in values)


sql = f"""-- Generated by scripts/export_postgres_seed.py — mirrors the SQLite security data.
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS incidents;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS identities;

CREATE TABLE identities(email TEXT PRIMARY KEY, name TEXT, department TEXT, role TEXT, mfa_enabled INTEGER);
CREATE TABLE assets(id TEXT PRIMARY KEY, name TEXT, type TEXT, business_unit TEXT, owner_email TEXT, criticality TEXT);
CREATE TABLE incidents(id TEXT PRIMARY KEY, title TEXT, severity TEXT, status TEXT, asset_id TEXT, opened_by TEXT, ts TEXT);
CREATE TABLE alerts(id SERIAL PRIMARY KEY, incident_id TEXT, source TEXT, signal TEXT);

INSERT INTO identities(email,name,department,role,mfa_enabled) VALUES
{rows(s.IDENTITIES)};

INSERT INTO assets(id,name,type,business_unit,owner_email,criticality) VALUES
{rows(s.ASSETS)};

INSERT INTO incidents(id,title,severity,status,asset_id,opened_by,ts) VALUES
{rows(s.INCIDENTS)};

INSERT INTO alerts(incident_id,source,signal) VALUES
{rows(s.ALERTS)};
"""

with open(OUT, "w") as f:
    f.write(sql)
print(f"wrote {OUT}  ({len(s.INCIDENTS)} incidents, {len(s.ASSETS)} assets, {len(s.IDENTITIES)} identities)")
